### ISSUE TITLE
Enable tab completion via CLI to `System.CommandLine` Migration 

### ISSUE THREAD

**Issue by antonrademaker** [dotnet/templating#2191]
Dotnet cli supports tab completion, it would be really handy to have support for template parameters / symbols as well?

https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete

To allow tab completion, dotnet new CLI needs to migrate to [System.CommandLine parser](https://github.com/dotnet/command-line-api).

### Done
- [x] https://github.com/dotnet/templating/issues/3802
- [x] https://github.com/dotnet/templating/issues/3805
- [x] https://github.com/dotnet/templating/issues/3806
- [x] https://github.com/dotnet/templating/issues/3807
- [x] https://github.com/dotnet/templating/issues/3804
- [x] https://github.com/dotnet/templating/issues/3803
- [x] https://github.com/dotnet/templating/issues/3811
- [x] https://github.com/dotnet/templating/issues/2983
- [x] https://github.com/dotnet/templating/issues/3810
- [x] https://github.com/dotnet/templating/issues/3263
- [x] https://github.com/dotnet/templating/issues/3809
- [x] https://github.com/dotnet/templating/issues/4060
- [x] binding arguments for host/telemetry https://github.com/dotnet/templating/pull/4254
- [x] https://github.com/dotnet/templating/issues/3812
- [x] https://github.com/dotnet/templating/issues/3053
- [x] https://github.com/dotnet/templating/issues/4034
- [x] https://github.com/dotnet/templating/issues/3814 - done by @baronfel 
- [x] https://github.com/dotnet/templating/issues/3813

### Not started / moved to separate issues

- [ ] use `IConsole` instead of `Reporter` - https://github.com/dotnet/templating/issues/4999
- [ ] consider creating `TemplatePackageManager.GetTemplates` version which uses cache only for tab completion and help
  - consider implementing non async version for GetTemplatePackage based on cache to be used in `HandleAmbiguousTemplateGroup` and `HandleAmbiguousResult` methods. At the moment help delegate is not async, also not possible to use async methods in renderer. https://github.com/dotnet/templating/pull/4227#discussion_r774514926
  - https://github.com/dotnet/templating/issues/4999
- [ ] implement [parse] and [suggest] directives - https://github.com/dotnet/templating/issues/4999
- [ ] fix colouring for error messages for help - https://github.com/dotnet/templating/issues/4999
- [ ] https://github.com/dotnet/templating/issues/4219
- [ ] https://github.com/dotnet/templating/issues/4225
- [ ] address https://github.com/dotnet/command-line-api/pull/1582: add corresponding calls to unit tests / re-parsing calls - https://github.com/dotnet/templating/issues/4999
- [ ] use middleware for debug options, building environment settings, etc. - https://github.com/dotnet/templating/issues/4999
- [ ] review parsing of template options, some considerations - https://github.com/dotnet/templating/issues/4999
     - default if option without value should not be parsed / validated at parser level. Instead the parser should just pass `null` in this case and `TemplateCreator` should handle this case properly. However if default if option without value is not set for parameter, having no value for option should not be allowed.
     - consider not parsing hex values on parser level. It's a specific format of current generator. Either utilize generator to see if value can be parsed or try to convert any value to hex in format needed by generator and fail if it's not possible.
     - points above should allow to remove custom parse logic for most cases.

## Justification
**Customer impact**
1.  better and more intuitive CLI UX, including help
1.  enables tab completion
**Engineering impact**
1. removes dependency on old parser, requiring workarounds for source-build and separate repo maintanence costs
1. easier cost of adding new commands and options for new features

**Comment by rainersigwald** [comment]
Another upvote from Twitter: https://twitter.com/buhakmeh/status/1235581946853392386?s=20

cc @donJoseLuis

**Comment by donJoseLuis** [comment]
we need to find the right place for this issue.

**Comment by donJoseLuis** [comment]
## May also resolve:
- [x] https://github.com/dotnet/templating/issues/1926
- [ ] https://github.com/dotnet/templating/issues/1704
- [x] https://github.com/dotnet/templating/issues/1544
- [x] https://github.com/dotnet/templating/issues/4128 - uninstall recommendation on conflict part (duplicate: https://github.com/dotnet/templating/issues/3275)
- [ ] https://github.com/dotnet/templating/issues/4155 - issue with improper help display
- [ ] https://github.com/dotnet/templating/issues/4135

## Blocks:
- https://github.com/dotnet/templating/issues/2720
- https://github.com/dotnet/templating/issues/2038
- https://github.com/dotnet/templating/issues/2173
- https://github.com/dotnet/templating/issues/3009

**Comment by vlada-shubina** [comment]
This effort is considered to be done. Outstanding items from description / comments are moved to separate issues and will be done later.
