### ISSUE TITLE
Epic: Support optional SDK workload

### ISSUE THREAD

**Issue by grinrag** [dotnet/templating#2429]
[Workloads overview spec](https://github.com/dotnet/designs/pull/100)

This Epic tracks the work needed for the Template Engine to support Optional Workload templates.

- [x] [Add design doc for the Template Engine](https://github.com/dotnet/templating/issues/2378)
- [ ] [Intergrate with the Optional Workload Library to query API](https://github.com/dotnet/templating/issues/2428)
- [ ] [Add autoinstallation/autoupdate of OW templates in the Hive for .Net 5](https://github.com/dotnet/templating/issues/2405)
- [ ] [Extend Hive cache with additional information about OW template](https://github.com/dotnet/templating/issues/2426)
- [ ] [Perform autocleaning of cache (uninstall OW template)](https://github.com/dotnet/templating/issues/2427)

#### Testing phase

We need to complete the Tests:
- for the integration with real Optional SDK Workloads installation.
- perf test for installation/uninstallation (invoke the API call on every run, invoke cache cleaning on every run). The perf test should take into account number of templates installed in a system.
