### ISSUE TITLE
[EPIC] The list of commits to cherry-pick into RC2

### ISSUE THREAD

**Issue by grinrag** [dotnet/templating#2480]
- [x] [Update information in the listing when the type parameter was provided](https://github.com/dotnet/templating/issues/2457)
- [x] [closing a condition block on the last line of file fails when followed by a blank line](https://github.com/dotnet/templating/issues/1641)
- [x] [When there is exact match by short name other partial names are not shown in list ](https://github.com/dotnet/templating/issues/2491)
- [x] [Update error messages in the listing when no exact match and partial match by name is found but mismatch --type and/or --language](https://github.com/dotnet/templating/issues/2472)
- [x] [Inconsistent error messages when filtering the listing](https://github.com/dotnet/templating/issues/2471)
- [x] [Show warning if no template name or any parameter was provided to dotnet new](https://github.com/dotnet/templating/issues/2353)
- [x] [update help output for 'dotnet new -h'](https://github.com/dotnet/templating/issues/2342)
- [x] [ Mistyping a template parameter results in overly verbose and confusing error message ](https://github.com/dotnet/templating/issues/2408)

**Comment by grinrag** [comment]
commits were cherry-picked to RC2 from master (some of the commits fix several issues):

76e76fb9750452afc3aa1ed8c3a1562432dfb3af
fe083b8248e6d0df2f21da4bb4fa2421962422ac 
fefce1b5513c6aafeeb721fc026548b3318fceff 
3dd2e5a7e6c2b99d3c2e6114b812c95259604d99 
ac1d672ddfe6d6b16b9238bf4f3bb1044f4a7b12 
fa3b31474dde9ae5e3dcfc9aae5c6791dc0cc7f8
