### ISSUE TITLE
As a customer, I want a "--search" option, so that Internet searches are no longer a default

### ISSUE THREAD

**Issue by AR-May** [dotnet/templating#2483]
We would like to implement an option for an online search on [NuGet.](https://www.nuget.org/)

### Requirements ###
1. Introduce `--search` option for `dotnet new` to allow explicit search for the templates on NuGet.org
    1. It is possible to search template by template name (short and full)
    1. The following filters are supported: language, type, author (including partial matches), package name (including partial matches), tags (including partial matches)
    1. The search results are displayed as a table
        1. The table columns are shrunk in case of long data 
    1. The search results include number of downloads
    1. The output features the example on how to install the templates
    1. The user can control which columns to be shown
1. On template instantiation: if the template is not found in local cache,  "No template" error message should be shown.
1. Download of search cache file is not done on template instantiation error
1. Search cache file is only downloaded when there is an update
1. Documentation and help reference is updated to include `--search` option

### Non-goals ###
1. Changing the search method from using template search cache file (updated each 2 weeks) to directly use NuGet API (template search is not available at the moment)
1. Automating creation of template search cache file (currently it is update manually)

---

- [x]  Update manually the metadata file and fix the current problem with the out-of-date file. Related issue: #2464.
- [x]  Implement an option `--search` for online search and drop searching on the internet as a default behavior. https://github.com/dotnet/templating/issues/2571
- [x]  Change the downloading behavior. The metadata file should be checked for updates only if the `--search` option is present. Then, the metadata file should be downloaded only if it differs from the local version.
- [ ]  Update documentation. https://github.com/dotnet/templating/issues/2896
- [x] Add example for searching the templates on nuget to help message for missing template https://github.com/dotnet/templating/issues/2519
- [x] https://github.com/dotnet/templating/issues/2558
- [ ] Unit tests https://github.com/dotnet/templating/issues/2898
- [ ] Integration tests https://github.com/dotnet/templating/issues/2897
