### ISSUE TITLE
[EPIC] Fix post actions

### ISSUE THREAD

**Issue by AR-May** [dotnet/templating#2490]
There are plenty of issues concerning post actions. Here is an EPIC where we will track them all:

- [ ]  Bug: Post action "Add projects to a solution file" does not work with `-o` option.
- [ ]  [Bug](https://github.com/dotnet/templating/issues/1991): In post action "Add projects to a solution file" `primaryOutputs` are not updated with `sourceName`.
- [ ]  [Bug](https://github.com/dotnet/templating/issues/2068): In post action "Restore NuGet packages" `primaryOutputs` are not updated with `sourceName`.
- [ ]  [Bug](https://github.com/dotnet/templating/issues/1663): Post action "Run script" does not work with `"preferNameDirectory" : "true"`, and, probably, with `-o` option as well.
- [ ]  [Feature](https://github.com/dotnet/templating/issues/2274): For post action "Add projects to a solution file" add an option for specifying the solution directory. 
- [ ]  [Feature](https://github.com/dotnet/templating/issues/1896): Loss of functionality in post action "Restore NuGet packages".

**Comment by StingyJack** [comment]
I would like to add "Some documentation artifact that clearly explains what a post action is and what it does"  I can read through a bunch of code and issues here and glean some understanding but there isnt anything I can find that says what they are.
