### ISSUE TITLE
Disable partial matching in CLI

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2494]
## As a customer, I want disable partial name matching when creating the template, for a more intuitive experience 

At the moment creating the template by unambiguous partial name works
Example: `dotnet new class` --> creates the `classlib` project

Epic to change the behavior to allow only exact match for template creation.
Partial match should show help/ string to use to create the template

#### Functional requirements ####
1. It should be only possible to instantiate template using exact match on the template short name.
1. The partial match should not instantiate the template, the proper error message should be shown.
1. Only exact match on template options (parameters) and their values are allowed, the partial matches are forbidden.
1. Documentation and tutorials should be updated to reflect the changes 

#### Technical requirements ####
1. Consider finalizing template resolution refactoring started in [dotnet/templating#2558](https://github.com/dotnet/templating/issues/2558)
    1. Implement supported filters list for help and instantiation (in addition to list and search), revise the filters applied for each case.
        1. For example: classification filter doesn't make sense for help and instantiation, however makes sense for list and search.
    1. Move template resolution logic to `TemplateResolver` and `TemplateListResolver` classes from `TemplateResolutionResult` and `TemplateListResolutionResult` respectively. `Result` classes should contain only result artifacts.
    1. Implement filtering by classification [dotnet/templating#2475](https://github.com/dotnet/templating/issues/2475) for list and search
1. Create tech reference for template resolution rules

Sub tasks:

- [x] https://github.com/dotnet/templating/issues/3113
- [x] https://github.com/dotnet/templating/issues/3114
- [x] https://github.com/dotnet/templating/issues/2493
- [ ] https://github.com/dotnet/templating/issues/3116
- [x] https://github.com/dotnet/templating/issues/3117
