### ISSUE TITLE
As a templating owner, I want to revise how optional parameters checks are done, to ensure best code quality

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2505]
#### Functional requirements ####
- [ ] In case choice parameter has only one value it should be anyway shown in template help --> moved to https://github.com/dotnet/templating/issues/3810
- [x] Review template options matching rules

#### Technical requirements ####

- [ ] Template options should be validated consistently. Now the choice parameters are validated during template resolution and other types are validated only during template instantiation. --> moved to respective tasks in migration to new parser.
- [x] `ITemplateInfo` interface improvements:
    1. separate language and type as the separate properties
    1. separate tags, classifications and choice parameters to respective properties
    1. define proper naming configuration for classifications vs. tags - now classifications is presented as tags for users.
    1. consider merging some interfaces: there are several interfaces containing 1-2 properties which add features to the main functionality, however they are not implemented in all respective places in CLI [#2732](https://github.com/dotnet/templating/issues/2732) and not implemented in IDE API.
- [ ] Consider refactoring for template help display: the logic is overcomplicated, mentions TODO's in the code and need of refactoring. --> moved to https://github.com/dotnet/templating/issues/3810
    1. Effectively the code almost runs the template to get the help, which leads to performance hit.
    1. Consider designing special API to validate the user input in Orchestrator instead
- [x] Document the rules for template options matching on template resolution for all scenarios (related to open item #2)
- [x] Cover template help display (display template specific options) with integration tests

**Comment by vlada-shubina** [comment]
Closing the epic:
- most of tasks are already done
- other tasks will anyway be done when migrating to new parser.
