### ISSUE TITLE
[doc] CustomOperations and SpecialCustomOperations

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2516]
- [ ] document custom operations and special custom operations in Wiki
- [ ] https://github.com/dotnet/templating/issues/282 close issue with reference to documentation
- [ ] https://github.com/dotnet/templating/issues/2090
- [ ] https://github.com/dotnet/templating/issues/1775
- [ ] update JSON schema https://github.com/dotnet/templating/issues/2514
- [ ] https://github.com/dotnet/templating/issues/999

Helpful information:
https://github.com/dotnet/templating/issues/1237
https://github.com/dotnet/templating/issues/2208#issuecomment-644861881
https://github.com/dotnet/templating/issues/286
https://github.com/dotnet/templating/issues/237#issuecomment-277070311

**Comment by donJoseLuis** [comment]
Related to peer User Story: - [ ] update JSON schema https://github.com/dotnet/templating/issues/2514
