### ISSUE TITLE
[epic] Add support for template locale

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2542]
- [ ] implement template option to specify locale
- [ ] implement support of host locale for user entered values
- [ ] unit tests
- [ ] documentation update
- [ ] JSON schema update

**Comment by vlada-shubina** [comment]
Not required at the moment, closed.
