### ISSUE TITLE
[Epic] Automate regular updates of NuGetTemplateSearchInfo.json file 

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2572]
At the moment NuGetTemplateSearchInfo.json can only be updated manually. 

Consider automating it to be updated on regular basis without manual interaction.

- [x] Create a build pipeline to automate the publishing of the old cache file format. https://github.com/dotnet/templating/issues/3229
- [x] Remove unnecessary fields from the cache file, update the engine to read the new cache file format -> search v2 https://github.com/dotnet/templating/issues/3230
- [x] Compress the cache file in the blob storage, update the engine to unzip the cache file upon download https://github.com/dotnet/templating/issues/3231
- [x] Automate updating the cache file in the blob storage using build pipelines https://github.com/dotnet/templating/issues/3232
- [x] [NTH] Update build pipeline to do incremental updates (don't download everything at every run). This will allow much frequent updates to the file. https://github.com/dotnet/templating/issues/3233
- [x] https://github.com/dotnet/templating/issues/3493
- [x] https://github.com/dotnet/templating/issues/3249
- [x] https://github.com/dotnet/templating/issues/3229

**Comment by vlada-shubina** [comment]
Deferred until early next year, manual update to be done until that. Potentially this functionality might be implemented in Nuget service
