### ISSUE TITLE
Use NuGet API for interactions with NuGet (install / update-*)

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2592]
### Requirements ###
1. Check for the update retrieves the information from NuGet feed directly - there is no delay in retrieving update availability due to outdated template search cache.
1. The template packs should be downloaded using NuGet API instead of using dotnet restore
    1. Download from private NuGet feed is supported
    1. Interactive authorization (--interactive) is supported
1. Checking the updates using `--update-check` is supported for the packages installed from private NuGet feeds.
1. Installing the updates using `--update-apply` is supported for the packages installed from private NuGet feeds.

- [ ] Modify NuGet installer to support multiple download / update implementation https://github.com/dotnet/templating/issues/2812 - on hold, might be not needed if integration using API is stable.
- [x] Implement `IDownloader` interface for downloading packages directly using NuGet API (public feed, private feeds, local feeds) https://github.com/dotnet/templating/issues/2813
- [x] Implement `IUpdater` interface for checking for update directly using NuGet API (public feed, private feeds, local feeds) https://github.com/dotnet/templating/issues/2814
- [x] Add interactive auth support https://github.com/dotnet/templating/issues/2816
- [x] Reading NuGet soruces configuration: https://github.com/dotnet/templating/issues/2856
- [ ] Unit tests (public feed, local feed, private feed?)
- [x] Integration tests for --install, --update-apply, --update-check (dotnet-new3) https://github.com/dotnet/templating/issues/2816

Fixes the following items:
https://github.com/dotnet/templating/issues/2308
https://github.com/dotnet/templating/issues/2398
https://github.com/dotnet/templating/issues/2369
https://github.com/dotnet/templating/issues/1538
https://github.com/dotnet/templating/issues/1084
