### ISSUE TITLE
Improve the template engine authoring experience as it relates to the developer inner-loop

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#2637]
### Summary
The .NET template authoring experience impacts the overall inner-loop experience. .NET developers who author and maintain templates are quite passionate and active in the community.  We should explore opportunities for improving feedback attained during template development.

_**Note**_: This is a draft/proposed _epic_ and not committed for .NET 6.0 yet.

### User Stories
User Stories under this Epic:
- [ ] [As a customer, I want new capabilities to improve my template authoring experience ](https://github.com/dotnet/templating/issues/2638)
- [ ] [As a contributor, I want end-to-end testing capabilities to ensure quality in my development](https://github.com/dotnet/templating/issues/2639)
- [ ] [As a customer, I want to explicitly ask for templates on nuget.org to easily install what I want](https://github.com/dotnet/templating/issues/2640)
- [ ] [As a customer, I want projects from authored templates to default to .NET 6.0 to avoid me having to do so manually](https://github.com/dotnet/templating/issues/2641)

**Comment by donJoseLuis** [comment]
Abandoned, this work will be tracked via other means.
