### ISSUE TITLE
Template Engine contributes to a .NET CLI "Natural" experience

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#2642]
### Summary
All aspects of the Template Engine, `dotnet new`, template authoring, and engine API should contribute to the desired NATURAL CLI UX.

- Developers see template information in the culture/language set for the CLI
- Developers can use tab completion for the templates themselves
- Developers always (or almost always) have good tab completion available
- CLI behavior matches highest expectations for experienced command line developers, even if unfamiliar with, and especially Linux users

_**Note**_: This is a draft/proposed _epic_ and not committed for .NET 6.0 yet.

### User Stories
User Stories under this Epic:
- [ ] [As a customer, I want dotnet new to support tab completion to increase my productivity](https://github.com/dotnet/templating/issues/2644)
- [ ] [As a customer, I want dotnet new to behave as standard cmd tools to increase my productivity](https://github.com/dotnet/templating/issues/2643)
- [ ] [As a customer, I want template information in the locale set for the CLI to improve my productivity with the tool](https://github.com/dotnet/templating/issues/2645)
- [ ] [As a customer, I want installation support in the engine for Workloads templates to enable familiar development UX with new workloads](https://github.com/dotnet/templating/issues/2646)

**Comment by donJoseLuis** [comment]
Abandoned, this work will be tracked via other means.
