### ISSUE TITLE
Updating public APIs

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#2868]
Review public members of libraries published to NuGet:
+ make a decision on what public APIs should remain public, document them (in the code)
+ there are a lot of public methods that are no use externally, they should be moved to internal use.
+ marking async methods as <method name>Async
+ adding CancellationToken to the methods 
+ review ITemplateEngineHost interface

- [x]  https://github.com/dotnet/templating/issues/2996
- [x]  https://github.com/dotnet/templating/issues/2997
- [x]  https://github.com/dotnet/templating/issues/2998
- [x]  https://github.com/dotnet/templating/issues/2999
- [x]  https://github.com/dotnet/templating/issues/3000
- [x]  https://github.com/dotnet/templating/issues/3001
- [x]  https://github.com/dotnet/templating/issues/3002

**Comment by vlada-shubina** [comment]
Notes:

**Generic**:
- ensure all public APIs are documented
- ensure all async methods use Cancellation tokens
- move tools to `tools` folder

`Abstractions` notes:
- create new version of `ITemplateEngineHost` (including logger, removing unused features etc)
- remove duplicate interfaces (e.g. `ITemplatewithTimestamp`)
- ? should we split interfaces to be used for components from interfaces to be used when implementing host?

`Cli` notes:
- make everything internal except method used in SDK\dotnet-new3
- ? should we move Cli to SDK repo?

`Core` and `Core.Contracts` notes:
- suggesting either do not touch (preferred) or make everything internal and internals visible to assemblies

`Edge`:
- make all implementations internal

`IDE`:
- probably no work, except documentation
- should we discuss with VS to deprecate it and use Edge instead?

`Orchestartor.RunnableProjects`:
- make all implementations and interfaces internal 

`Utils`:
- document, remove obsolete
- should we group them? 

`TemplateSearch.Common`:
- suggesting stop shipping it as it belongs only to search blob cache
- make required interfaces to be used by the host/tools
- make everything else internal
