### ISSUE TITLE
[Epic] Localizing .NET templates

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#3361]
Contains tasks related to localizing .NET templates shipped with dotnet sdk

- [x] https://github.com/dotnet/templating/issues/3243
- [ ] https://github.com/dotnet/templating/issues/3270
- [x] https://github.com/dotnet/templating/issues/3455
- [ ] https://github.com/dotnet/templating/issues/3448
- [x] https://github.com/dotnet/templating/issues/3363
- [ ] https://github.com/dotnet/templating/issues/2819
- [x] https://github.com/dotnet/templating/issues/3178
- [x] https://github.com/dotnet/templating/issues/3269
- [x] https://github.com/dotnet/templating/issues/3271
- [x] https://github.com/dotnet/templating/issues/3483

**Comment by vlada-shubina** [comment]
closed, moved remaining tasks to #4283
