### ISSUE TITLE
 `dotnet new search`  output should display the template package owner

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#3456]
`dotnet new search`  output should display the template package author as a separate column together with template author. 
If user opts-in to show author, both columns should be shown. Package author should be shrinkable up to 15 chars.

- [x] adapt discovery tool to contain package owner https://github.com/dotnet/templating/commit/e59524670fafa7d0cfcd472276696a91be17d377
- [x] adapt search output 
- [ ] change documentation on docs.microsoft.com

**Comment by baronfel** [comment]
TODO for @baronfel: check the search cache file and identify templates where these two fields are different to get an idea of how prevalent this is. If rare, consider not doing UI treatment for this, and span the `--author <blah>` search query across the template author and package author fields transparently to the user.

**Comment by YuliiaKovalova** [comment]
implementation notes: CliTemplateSearchCoordinator is responsible for data output to console

**Comment by YuliiaKovalova** [comment]
@baronfel , we are pending vision for the output here.

**Comment by baronfel** [comment]
I'm not convinced that this is a large enough problem for us to do - we should check the things mentioned [here](https://github.com/dotnet/templating/issues/3456#issuecomment-1097145359) before going any further with this. If there are enough differences, then in the table we should concat all authors (template and package) together, and in the proposed #5861 we can show the difference between the template authors and the package authors.

**Comment by YuliiaKovalova** [comment]
Hi @baronfel, 

Please observe a couple of options for displaying package owners:
1) Merge template author and package owners
![image](https://user-images.githubusercontent.com/95473390/226336705-2c77de1d-2485-4739-bb16-0dfecddab46d.png)
![image](https://user-images.githubusercontent.com/95473390/226336940-70d9c055-7367-4788-977d-a6b0b7d1ba31.png)

2) Merge package name and package owners - helps to keep left side with tempate info only and the right side is populated with package-related data 
![image](https://user-images.githubusercontent.com/95473390/226360847-f15f818e-5603-4553-8ef8-fa07591e56e5.png)

3) @vlada-shubina suggests to remove Author at all from this search output and merge all package-related data in a single column (please take a look at added checkmark):
![image](https://user-images.githubusercontent.com/95473390/226374872-13707ed0-c444-4ac4-acbb-e801fc04f2ba.png)

Which option do you prefer?
