### ISSUE TITLE
Docs needed in wiki

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/templating#390]
We should improve [wiki](https://github.com/dotnet/templating/wiki) in the following ways. These are not listed in any order currently, but we should try and prioritize them soon.

 - [ ] #384 - Improve content in [main wiki page](https://github.com/dotnet/templating/wiki)
 - [x] #385 - Reference for comment syntax used for each file type.
 - [x] #386 -  Reference for available macros, ex now, randomnumber, etc
 - [x] #387 - Reference for available PostActions
 - [ ] #388 - Doc for best practices
 - [ ] #389 - How to create a template and share it on NuGet
 - [x] #392 - Samples doc

I've created an issue for each and marked with [docs](https://github.com/dotnet/templating/labels/docs) and [help-wanted](https://github.com/dotnet/templating/labels/help%20wanted). If you're interested in authoring one of the docs please comment back and I'll add the [assigned](https://github.com/dotnet/templating/labels/assigned) label.

@mlorbetske @seancpeters any other ideas for docs that we need here? FYI I'm already working on formal docs for running and creating templates. The idea here is to provide some more details here than what we can get from formal docs.

cc  @chad-ramos @RehanSaeed

**Comment by chad-ramos** [comment]
@sayedihashimi - What about a section for Configuration?  Right now it is jammed in the [Runnable Project](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates) page.  It would be easier to reference an individual page dedicated to the topic as opposed to a mixture of concerns.

**Comment by RehanSaeed** [comment]
I would add:

* Links to simple and more advanced example templates.

**Comment by mlorbetske** [comment]
Let's make sure to cover tags (and which ones are special in the different environments) and the meaning of preferNameDirectory.

**Comment by donJoseLuis** [comment]
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment]
This issue acts a parent "epic" to the tracked issues.  We'll include the issues in the road map & close this item, as in it's own is not actionable.
