### ISSUE TITLE
Reenable skipped tests in feature/command-line

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#4187]
#### Help

- [x] help cannot return exit code - discussed in https://github.com/dotnet/templating/pull/4143#discussion_r765899056
CannotShowHelpForTemplate_PartialNameMatch :white_check_mark:
CannotShowHelpForTemplate_FullNameMatch :white_check_mark:
CannotShowHelpForTemplate_WhenAmbiguousLanguageChoice  :white_check_mark:

- [x] error cases for help - https://github.com/dotnet/templating/issues/3809 (error handing for invalid parameters, ambiguous template logic, ambiguous template group logic)
CannotShowHelpForTemplate_WhenAmbiguousLanguageChoice  :white_check_mark:
CannotShowHelpForTemplate_MatchOnNonChoiceParamWithoutValue :white_check_mark:
CannotShowHelpForTemplate_MatchOnUnexistingParam :white_check_mark:
CannotShowHelpForTemplate_MatchOnChoiceWithoutValue :white_check_mark:

#### Instantiation

- [x] error cases for instantiation - https://github.com/dotnet/templating/issues/3809 (error handing for invalid parameters, ambiguous template logic, ambiguous template group logic)
CannotInstantiateTemplateWithUnknownLanguage  :white_check_mark:
CannotInstantiateTemplate_WhenAmbiguousLanguageChoice  :white_check_mark:
CannotInstantiateTemplate_WhenParameterIsInvalid :white_check_mark:
CannotInstantiateTemplate_WhenChoiceParameterValueIsInvalid :white_check_mark:
CannotInstantiateTemplate_WhenChoiceParameterValueIsNotComplete :white_check_mark:
CannotInstantiateTemplate_OnMultipleParameterErrors :white_check_mark:
CannotInstantiateTemplate_WhenPrecedenceIsSame  :white_check_mark:

- [ ] alias is not implemented - https://github.com/dotnet/templating/issues/3813
CanInstantiateTemplate_WithAlias

- [x] `--allow-scripts` option is not implemented - https://github.com/dotnet/templating/issues/3809 (implement --allow-scripts option if the template has run-script post action)
PostActionTests.RunScript_Basic
PostActionTests.RunScript_DoNotRedirect
PostActionTests.RunScript_Redirect
PostActionTests.RunScript_RedirectOnError

 
### Unit tests
- [x] https://github.com/dotnet/command-line-api/issues/1494
TabCompletionTests.Update_GetAllSuggestions
TabCompletionTests.TemplateCommand_GetAllSuggestions

- [ ] https://github.com/dotnet/command-line-api/issues/1496
TabCompletionTests.Instantiate_CanSuggestLanguages

- [x] https://github.com/dotnet/command-line-api/issues/1497 https://github.com/dotnet/command-line-api/issues/1519
TabCompletionTests.CanCompleteChoice_FromSingleTemplate_InTheMiddle

- [ ] https://github.com/dotnet/command-line-api/issues/1495
TabCompletionTests.Install_GetSuggestionsAfterInteractive
TabCompletionTests.Install_GetSuggestionsAfterOptionWithArg

- [x] https://github.com/dotnet/command-line-api/issues/1518
TabCompletionTests.Instantiate_CanSuggestTemplateOption_StartsWith

- [ ] https://github.com/dotnet/templating/issues/4192
TabCompletionTests.CanCompleteParameters_StartsWith_AfterOption

- https://github.com/dotnet/command-line-api/issues/1474
InstantiateTests.CanEvaluateInvalidParameters (1 data set)

- https://github.com/dotnet/command-line-api/issues/1503
ListTests.List_CanParseColumns (3 data sets)
SearchTests.List_CanParseColumns (3 data sets)

- https://github.com/dotnet/command-line-api/issues/1609
CanDetectParseErrorsChoiceTemplateOptions (1 data set)

Not in scope: tests disabled by https://github.com/dotnet/templating/issues/4061.
