### ISSUE TITLE
Improve Authoring UX

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#4281]
# Background
Deliver the template authoring experiences improvements. User Stories:
- [x] https://github.com/dotnet/templating/issues/4282
- [x] https://github.com/dotnet/templating/issues/4308
- [x] https://github.com/dotnet/templating/issues/3868

**Comment by JanKrivanek** [comment]
All planned work is done
