### ISSUE TITLE
Onboard template repos for localization

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#4308]
# Background
- [x] Escaping special characters are working https://github.com/dotnet/templating/pull/4267
- [x] We still don't respect the BOM of the original file. If the file has any changes, there will additionally be 1 more change - Bom. Fix: https://github.com/dotnet/templating/pull/4318 
- [x] Arcade repo needs to be updated to use the latest version of TE.Tasks package. This is mandatory for winforms repo. https://github.com/dotnet/arcade/blob/c2af37f76cedd4eb197857ae04e6fc534b0131ad/eng/Versions.props#L92
   - [x] Arcade PR is up (https://github.com/dotnet/arcade/pull/8395)
   - [x] Arcade PR is merged
   - [x] Arcade with the fixed TE.Tasks has flown into the winforms repo
- [x] We need to reenable localization on winforms repo (@bekir-ozturk has this locally) (previous PR: https://github.com/dotnet/winforms/pull/6319) - https://github.com/dotnet/winforms/pull/6622
- [x]  enable localization on test-templates - https://github.com/dotnet/test-templates/pull/220
- [x]  enable localization on wpf - https://github.com/dotnet/wpf/pull/5996
- [x]  enable localization on aspnetcore https://github.com/dotnet/aspnetcore/pull/38867
   - [x] check if it was applied for: `Web.ProjectTemplates` `Web.ItemTemplates`, `Client.ItemTemplates`
   - [ ] check if it was applied for: `Spa.ProjectTemplates`,
   - [ ] Repo needs to be onboarded to OneLocBuild. Tracked here: https://github.com/dotnet/aspnetcore/issues/36998
- [x] enable localization maui https://github.com/dotnet/maui/pull/4439
- [x] enable localization ios https://github.com/xamarin/xamarin-macios/pull/14213
- [ ] enable localization android - https://github.com/xamarin/xamarin-android/pull/6677

## Tasks
- [ ] create documentation on how to onboard the repos for localization: https://github.com/dotnet/templating/issues/2819
- [ ] update `Microsoft.TemplateEngine.Tasks` in arcade \ set up subscription.

## Justification
- Customer impact - templates appears localized in Visual Studio and dotnet new.
- Engineering impact - localization process is fully automatic

**Comment by vlada-shubina** [comment]
All the repos except xamarin/android were onboarded. For xamarin/android onboarding to OneLocBuild should be done first. The PR introducing localization for templates was made.
