### ISSUE TITLE
CLI UX improvements

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#4887]
## Tasks
The issue collects the tasks on CLI UX improvements
- [ ]  https://github.com/dotnet/templating/issues/3267 (8.0)
- [x] https://github.com/dotnet/templating/issues/2910 (8.0) 
- [ ] https://github.com/dotnet/templating/issues/5862 (8.0)
- [ ] https://github.com/dotnet/templating/issues/3418 (8.0)
- [ ] https://github.com/dotnet/templating/issues/5864 (8.0)
- [ ] https://github.com/dotnet/templating/issues/4854
- [ ] https://github.com/dotnet/templating/issues/4885
- [ ] https://github.com/dotnet/templating/issues/4501
- [ ] https://github.com/dotnet/templating/issues/4223
- [ ] https://github.com/dotnet/templating/issues/4135
- [x] https://github.com/dotnet/templating/issues/4061
- [x] https://github.com/dotnet/templating/issues/3456
- [ ] https://github.com/dotnet/templating/issues/3402
- [ ] https://github.com/dotnet/templating/issues/3262
- [ ] https://github.com/dotnet/templating/issues/3009
- [x] https://github.com/dotnet/templating/issues/2910
- [ ] https://github.com/dotnet/templating/issues/2909
- [ ] https://github.com/dotnet/templating/issues/2908
- [x] https://github.com/dotnet/templating/issues/2755
- [ ] https://github.com/dotnet/templating/issues/2720
- [ ] https://github.com/dotnet/templating/issues/3553
- [x] https://github.com/dotnet/templating/issues/4834
- [x] https://github.com/dotnet/templating/issues/4494
- [x] https://github.com/dotnet/templating/issues/3242
- [x] https://github.com/dotnet/templating/issues/3152
- [x] https://github.com/dotnet/templating/issues/3108

## Justification
1. Aligns with theme "Secure Supply Chain w/ NuGet"
2. Aligns with KR "Securing usage of packages across .NET projects"
3. Aligns with KR ".NET developers using Visual Studio are Extremely Satisfied"

**Comment by YuliiaKovalova** [comment]
Closing in favor of individual issues.
