### ISSUE TITLE
dotnet new SEARCH Improvements

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#5858]
## Tasks
- [x] https://github.com/dotnet/templating/issues/3456 (8.0)
- [x] https://github.com/dotnet/templating/issues/5859 (8.0)
- [x] https://github.com/dotnet/templating/issues/5860 (8.0)
- [x] https://github.com/dotnet/templating/issues/5861 (8.0)
- [x] https://github.com/dotnet/templating/issues/5863 (8.0)

## Justifications
1. Aligns with theme "Secure Supply Chain w/ NuGet"
2. Aligns with KR "Securing usage of packages across .NET projects"
