### ISSUE TITLE
Developers get NuGet package details in `dotnet new` search results

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#5861]
# Background
Ability to show NuGet package detailed information in `dotnet new search` \ list of installed NuGet packages, maybe even SBOM. 

# Justification
1. Trustworthiness improvement: New NuGet package details in `dotnet new` search results
2. Aligns to the `.NET secure supply chain with NuGet` OKRs

### Issues related

- [x]  https://github.com/dotnet/templating/issues/6683
 - [x] https://github.com/dotnet/templating/issues/6810
 - [x] https://github.com/dotnet/templating/issues/6813

**Comment by YuliiaKovalova** [comment]
A possible approach for implementation: add  new subcommand for displaying details like (details --packageIdentifier)
Also, for now, I suggest do not extend the cache with package details and request them by demand.

@baronfel, we need to discuss it with you + get clarity on what information should be displayed here.

**Comment by baronfel** [comment]
suggested api to prime the discussion:

```
dotnet new details <packageIdentifier> // note the packageIdentifier is required, so make it an argument and not an option
```

suggested output:

* author information
* license information (either link to license file if present, or link to URL of SPDX license text)
* Repo/Project link(s) if present in NuGet metadata (ProjectUrl property, Repository.Url metadata, etc)
* list templates in the package - foreach template, list
  * shortname(s)
  * tag(s)
  * language(s)

**Comment by baronfel** [comment]
sorry, you're of course correct - it should be top-level. I'll edit my original.

**Comment by YuliiaKovalova** [comment]
@baronfel, you bring a much wider scope with this idea:
1. uninstalled -> source is nuget.org
2. uninstalled -> source is a custom feed 
3. installed -> source is nuget.org
4. installed -> source is a local environment
5. installed -> source is a custom feed

Current estimation (S) implied supporting nuget.org only, but we can make a base for supporting other cases and implement them in separate stories.

cc : @vlada-shubina
