### ISSUE TITLE
Developers have secure `dotnet new` experiences with NuGet

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/templating#6250]
# User Stories
- [x] https://github.com/dotnet/templating/issues/5860
- [x] https://github.com/dotnet/templating/issues/5861
- [x] https://github.com/dotnet/templating/issues/5863
- [x] https://github.com/dotnet/templating/issues/6249

# Justification
1. Contributes to Theme "Secure Supply Chain with NuGet"
1. Contributes to & OKRs "Reduce the usage of vulnerable packages across .NET projects by 50%".
